### PR TITLE
Support for <3.11

### LINKED ISSUE #111: Support for <3.11
Remove the use of StrEnums in bot interface code to support python version <3.11. This is currently causing all the slash commands to break in the most recent version.

### PR DESCRIPTION
**Pull request by enskyeing**
Removed use of StrEnums to support earlier versions of python.

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
Can you remove the [bug note](https://discobase.zintensity.dev/#installation) from the documentation?

**Comment by ZeroIntensity** [comment]
This is an interesting way to do it. The easier fix is to use the enum values rather than string values in `create` e.g. `self.style == "default"` becomes `self.style == EmbedStyle.DEFAULT`

**Comment by enskyeing** [comment]
> This is an interesting way to do it. The easier fix is to use the enum values rather than string values in `create` e.g. `self.style == "default"` becomes `self.style == EmbedStyle.DEFAULT`

That's what it was originally lol. I thought I recalled someone complaining about doing it that way so I changed it to a string. Will change it back then.

**Comment by enskyeing** [comment]
Nevermind, I see what you mean.

**Comment by enskyeing** [comment]
> This is an interesting way to do it. The easier fix is to use the enum values rather than string values in `create` e.g. `self.style == "default"` becomes `self.style == EmbedStyle.DEFAULT`

you know this would've been the smarter way to do it now that I think about it lmao

**Review by ZeroIntensity — APPROVED** [review]
LGTM. Let's wait for all tests to pass before merging. Thank you, Skye!

**Pull request merged**
